name: Update IP List

on:
  schedule:
    - cron: '* */3 * * *'  # 每隔3小时运行一次
  workflow_dispatch:  # 手动触发
 # push: # 允许提交触发

jobs:

  update-ip-list:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
  
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install beautifulsoup4
        
    - name: Run collect_ips script
      run: python ${{ github.workspace }}/collect_ips.py

    - name: Commit and push changes
      run: |
        git config --global user.email "jinwyp@gmail.com"
        git config --global user.name "jinwyp"
        echo ${{ github.workspace }}
        ls -al
        git status --porcelain
        if [ -n "$(git status --porcelain)" ]; then
          git add *.txt
          git commit -m "Auto update CF IP list"
          git push
        else
          echo "No changes detected, skipping commit."
        fi
